version: '2'

services:
  db:
    image: 'postgres:latest'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - .env

  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - db
      - redis
    command: bundle exec sidekiq -q carrierwave
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  postgres:
  redis:
