version: '2'

services:
  db:
    image: 'postgres:latest'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - "4000:4000"
    volumes:
      - '.:/app'
    env_file:
      - .env

  app_stage:
    depends_on:
      - 'db'
      - 'redis_stage'
    build:
      context: .
      dockerfile: Dockerfile-stage
    ports:
      - "4001:4001"
    volumes:
      - '.:/app'
    env_file:
      - .env_stage

  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - db
      - redis
    command: bundle exec sidekiq -q carrierwave
    env_file:
      - .env

  sidekiq_stage:
    build: .
    volumes:
      - .:/app
    links:
      - db
      - redis_stage
    command: bundle exec sidekiq -q carrierwave
    env_file:
      - .env_stage

  redis:
    image: redis
    volumes:
      - 'redis:/var/lib/redis/data'

  redis_stage:
    image: redis
    volumes:
      - 'redis_stage:/var/lib/redis/data_stage'

volumes:
  postgres:
  redis:
  redis_stage:
