version: '2'

services:
  db:
    image: 'postgres:latest'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile-stage
    expose:
      - "4000"
    volumes:
      - '.:/app'
    env_file:
      - .env

  app_stage:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    expose:
      - "4001"
    volumes:
      - '.:/app_stage'
    env_file:
      - .env_stage

  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - db
      - redis
    command: bundle exec sidekiq -q carrierwave
    env_file:
      - .env

  sidekiq_stage:
    build: .
    volumes:
      - .:/app_stage
    links:
      - db
      - redis
    command: bundle exec sidekiq -q carrierwave
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - 'redis:/var/lib/redis/data'

  web:
    build:
      context: .
      dockerfile: /config/containers/Dockerfile-nginx
    links:
      - app
      - app_stage
    ports:
      - "80:80"

volumes:
  postgres:
  redis:
